// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: encoding.proto

package com.rulex.bsb.pojo;

public final class Encoding {
  private Encoding() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface eciesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.rulex.bsb.pojo.ecies)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes iv = 1;</code>
     */
    boolean hasIv();
    /**
     * <code>optional bytes iv = 1;</code>
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>optional bytes ephemPublicKey = 2;</code>
     */
    boolean hasEphemPublicKey();
    /**
     * <code>optional bytes ephemPublicKey = 2;</code>
     */
    com.google.protobuf.ByteString getEphemPublicKey();

    /**
     * <code>optional bytes ciphertext = 3;</code>
     */
    boolean hasCiphertext();
    /**
     * <code>optional bytes ciphertext = 3;</code>
     */
    com.google.protobuf.ByteString getCiphertext();

    /**
     * <code>optional bytes mac = 4;</code>
     */
    boolean hasMac();
    /**
     * <code>optional bytes mac = 4;</code>
     */
    com.google.protobuf.ByteString getMac();
  }
  /**
   * Protobuf type {@code com.rulex.bsb.pojo.ecies}
   */
  public  static final class ecies extends
      com.google.protobuf.GeneratedMessageLite<
          ecies, ecies.Builder> implements
      // @@protoc_insertion_point(message_implements:com.rulex.bsb.pojo.ecies)
      eciesOrBuilder {
    private ecies() {
      iv_ = com.google.protobuf.ByteString.EMPTY;
      ephemPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      mac_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int IV_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString iv_;
    /**
     * <code>optional bytes iv = 1;</code>
     */
    @Override
    public boolean hasIv() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes iv = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }
    /**
     * <code>optional bytes iv = 1;</code>
     */
    private void setIv(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      iv_ = value;
    }
    /**
     * <code>optional bytes iv = 1;</code>
     */
    private void clearIv() {
      bitField0_ = (bitField0_ & ~0x00000001);
      iv_ = getDefaultInstance().getIv();
    }

    public static final int EPHEMPUBLICKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString ephemPublicKey_;
    /**
     * <code>optional bytes ephemPublicKey = 2;</code>
     */
    @Override
    public boolean hasEphemPublicKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes ephemPublicKey = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getEphemPublicKey() {
      return ephemPublicKey_;
    }
    /**
     * <code>optional bytes ephemPublicKey = 2;</code>
     */
    private void setEphemPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      ephemPublicKey_ = value;
    }
    /**
     * <code>optional bytes ephemPublicKey = 2;</code>
     */
    private void clearEphemPublicKey() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ephemPublicKey_ = getDefaultInstance().getEphemPublicKey();
    }

    public static final int CIPHERTEXT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString ciphertext_;
    /**
     * <code>optional bytes ciphertext = 3;</code>
     */
    @Override
    public boolean hasCiphertext() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes ciphertext = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }
    /**
     * <code>optional bytes ciphertext = 3;</code>
     */
    private void setCiphertext(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      ciphertext_ = value;
    }
    /**
     * <code>optional bytes ciphertext = 3;</code>
     */
    private void clearCiphertext() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ciphertext_ = getDefaultInstance().getCiphertext();
    }

    public static final int MAC_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString mac_;
    /**
     * <code>optional bytes mac = 4;</code>
     */
    @Override
    public boolean hasMac() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes mac = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }
    /**
     * <code>optional bytes mac = 4;</code>
     */
    private void setMac(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      mac_ = value;
    }
    /**
     * <code>optional bytes mac = 4;</code>
     */
    private void clearMac() {
      bitField0_ = (bitField0_ & ~0x00000008);
      mac_ = getDefaultInstance().getMac();
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, iv_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, ephemPublicKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, ciphertext_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, mac_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, iv_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, ephemPublicKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, ciphertext_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, mac_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ecies parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ecies parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ecies parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ecies parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ecies parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ecies parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ecies parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ecies parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ecies parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ecies parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ecies parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ecies parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ecies prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.rulex.bsb.pojo.ecies}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ecies, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.rulex.bsb.pojo.ecies)
        eciesOrBuilder {
      // Construct using com.rulex.bsb.pojo.Encoding.ecies.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes iv = 1;</code>
       */
      @Override
      public boolean hasIv() {
        return instance.hasIv();
      }
      /**
       * <code>optional bytes iv = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString getIv() {
        return instance.getIv();
      }
      /**
       * <code>optional bytes iv = 1;</code>
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIv(value);
        return this;
      }
      /**
       * <code>optional bytes iv = 1;</code>
       */
      public Builder clearIv() {
        copyOnWrite();
        instance.clearIv();
        return this;
      }

      /**
       * <code>optional bytes ephemPublicKey = 2;</code>
       */
      @Override
      public boolean hasEphemPublicKey() {
        return instance.hasEphemPublicKey();
      }
      /**
       * <code>optional bytes ephemPublicKey = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getEphemPublicKey() {
        return instance.getEphemPublicKey();
      }
      /**
       * <code>optional bytes ephemPublicKey = 2;</code>
       */
      public Builder setEphemPublicKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEphemPublicKey(value);
        return this;
      }
      /**
       * <code>optional bytes ephemPublicKey = 2;</code>
       */
      public Builder clearEphemPublicKey() {
        copyOnWrite();
        instance.clearEphemPublicKey();
        return this;
      }

      /**
       * <code>optional bytes ciphertext = 3;</code>
       */
      @Override
      public boolean hasCiphertext() {
        return instance.hasCiphertext();
      }
      /**
       * <code>optional bytes ciphertext = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString getCiphertext() {
        return instance.getCiphertext();
      }
      /**
       * <code>optional bytes ciphertext = 3;</code>
       */
      public Builder setCiphertext(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCiphertext(value);
        return this;
      }
      /**
       * <code>optional bytes ciphertext = 3;</code>
       */
      public Builder clearCiphertext() {
        copyOnWrite();
        instance.clearCiphertext();
        return this;
      }

      /**
       * <code>optional bytes mac = 4;</code>
       */
      @Override
      public boolean hasMac() {
        return instance.hasMac();
      }
      /**
       * <code>optional bytes mac = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString getMac() {
        return instance.getMac();
      }
      /**
       * <code>optional bytes mac = 4;</code>
       */
      public Builder setMac(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMac(value);
        return this;
      }
      /**
       * <code>optional bytes mac = 4;</code>
       */
      public Builder clearMac() {
        copyOnWrite();
        instance.clearMac();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.rulex.bsb.pojo.ecies)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ecies();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ecies other = (ecies) arg1;
          iv_ = visitor.visitByteString(
              hasIv(), iv_,
              other.hasIv(), other.iv_);
          ephemPublicKey_ = visitor.visitByteString(
              hasEphemPublicKey(), ephemPublicKey_,
              other.hasEphemPublicKey(), other.ephemPublicKey_);
          ciphertext_ = visitor.visitByteString(
              hasCiphertext(), ciphertext_,
              other.hasCiphertext(), other.ciphertext_);
          mac_ = visitor.visitByteString(
              hasMac(), mac_,
              other.hasMac(), other.mac_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  bitField0_ |= 0x00000001;
                  iv_ = input.readBytes();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  ephemPublicKey_ = input.readBytes();
                  break;
                }
                case 26: {
                  bitField0_ |= 0x00000004;
                  ciphertext_ = input.readBytes();
                  break;
                }
                case 34: {
                  bitField0_ |= 0x00000008;
                  mac_ = input.readBytes();
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ecies> parser = PARSER;
          if (parser == null) {
            synchronized (ecies.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.rulex.bsb.pojo.ecies)
    private static final ecies DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new ecies();
    }

    public static ecies getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ecies> PARSER;

    public static com.google.protobuf.Parser<ecies> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
